### ISSUE TITLE
To-Do 

### ISSUE THREAD

**Issue by sallamander** [sallamander/neural-networks-intro#3]
- [x] Fix formulas to use big `N` as number of obs. (instead of `n`)
- [x] Use more obs. for training (will help converge faster, and just makes sense... maybe, check the timing of this)
- [x] Fix calculation of errors -  `1/2` should be included with the individual errors and not aggregate
- [x] Fix negative sign in `binary_crossentropy` for logistic regression 
- [x] Change usage of `logistic` function to `sigmoid`, and make a note explaining the terminology
- [x] Also explain the lack of explicit use of multiple logistic regression
- [x] Make sure previous notebooks are linked
- [x] Fix comments that are too long (e.g. go off page) in `2b` and `3b`
- [x] Check comments in other places
- [x] Consider a `Derivatives` section in the `b` notebooks, with distinctive sections for specific derivatives
- [x] Standardize use of `T.grad` in `c` notebooks (e.g. don't switch between `T.grad` and `theano.grad`)
- [ ] Consider explaining the `bias=False` parameter in Keras models in either chapters 1 or 2 of the 1st minibook. 
- [ ] Fix descriptions of fake data generation.
